/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author 80424
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    VitalSignHistory history;
    public CreateJPanel(VitalSignHistory vsh) {
        initComponents();
        this.history = vsh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        lblBp = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        lblConcious = new javax.swing.JLabel();
        fieldDate = new javax.swing.JTextField();
        fieldTemperature = new javax.swing.JTextField();
        fieldBp = new javax.swing.JTextField();
        fieldPulse = new javax.swing.JTextField();
        btnYes = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setText("Create Vital Sign");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        lblDate.setText("Date");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        lblTemperature.setText("Temperature");
        add(lblTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        lblBp.setText("Blood Presure");
        add(lblBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        lblPulse.setText("Pulse");
        add(lblPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, 20));

        lblConcious.setText("Concious Status");
        add(lblConcious, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));
        add(fieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 210, -1));
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 210, -1));

        fieldBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBpActionPerformed(evt);
            }
        });
        add(fieldBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 210, -1));

        fieldPulse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPulseActionPerformed(evt);
            }
        });
        add(fieldPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 210, -1));

        buttonGroup1.add(btnYes);
        btnYes.setSelected(true);
        btnYes.setText("Yes");
        add(btnYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        buttonGroup1.add(btnNo);
        btnNo.setText("No");
        add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBpActionPerformed

    private void fieldPulseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPulseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPulseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String date = fieldDate.getText();
        float temp = Float.parseFloat(fieldTemperature.getText());
        double bp = Double.parseDouble(fieldBp.getText());
        int pulse = Integer.parseInt(fieldPulse.getText());
        boolean isConscious;
        
        if(btnYes.isSelected()){
            isConscious = true;
        } else{
            isConscious = false;
        }
        
        VitalSign vs = history.addNewVital();
        vs.setDate(date);
        vs.setTemperature(temp);
        vs.setBloodPressure(bp);
        vs.setPulse(pulse);
        vs.setIsConcious(isConscious);
        
        JOptionPane.showMessageDialog(this, "New VitalSign added", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        fieldDate.setText("");
        fieldTemperature.setText("");
        fieldBp.setText("");
        fieldPulse.setText("");
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnSave;
    private javax.swing.JRadioButton btnYes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fieldBp;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldPulse;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JLabel lblBp;
    private javax.swing.JLabel lblConcious;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
