/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 80424
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    VitalSignHistory history;
    public ViewJPanel(VitalSignHistory vsh) {
        initComponents();
        this.history = vsh;
        populateTable();
    }

     private void populateTable() {
        DefaultTableModel model =(DefaultTableModel)tblVital.getModel();
        model.setRowCount(0);
        
        for(VitalSign vs: history.getHistory()){
            
            Object[] row = new Object[5];
            row[0] = vs.getDate();
            row[1] = vs.getTemperature();
            row[2] = vs.getBloodPressure();
            row[3] = vs.getPulse();
            row[4] = vs.isIsConcious();
            
            model.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVital = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        lblBp = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        lblConcious = new javax.swing.JLabel();
        fieldDate = new javax.swing.JTextField();
        fieldTemperature = new javax.swing.JTextField();
        fieldBp = new javax.swing.JTextField();
        fieldPulse = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Temperature", "Blood Pressure", "Pulse", "Conscious"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVital);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 700, 300));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel1.setText("View Vital Sign History");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        lblDate.setText("Date");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        lblTemperature.setText("Temperature");
        add(lblTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        lblBp.setText("Blood Presure");
        add(lblBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, -1, -1));

        lblPulse.setText("Pulse");
        add(lblPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, -1, 20));

        lblConcious.setText("Concious Status");
        add(lblConcious, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, -1, -1));
        add(fieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 210, -1));
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 210, -1));

        fieldBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBpActionPerformed(evt);
            }
        });
        add(fieldBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 210, -1));

        fieldPulse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPulseActionPerformed(evt);
            }
        });
        add(fieldPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 210, -1));
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 70, 20));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBpActionPerformed

    private void fieldPulseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPulseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPulseActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVital.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to view","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
        DefaultTableModel model = (DefaultTableModel) tblVital.getModel();
        VitalSign selectedVital = (VitalSign)model.getValueAt(selectedRow, 0);
        
        if (selectedVital != null){
            fieldDate.setText(selectedVital.getDate());
            fieldTemperature.setText(String.valueOf(selectedVital.getTemperature()));
            fieldBp.setText(String.valueOf(selectedVital.getBloodPressure()));
            fieldPulse.setText(String.valueOf(selectedVital.getPulse()));
            
            if(selectedVital.isIsConcious()){
                lblStatus.setText("Yes");
            } else{
                lblStatus.setText("No");
            }

    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVital.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete","Warning",JOptionPane.WARNING_MESSAGE);
        }
        DefaultTableModel model = (DefaultTableModel) tblVital.getModel();
        VitalSign selectedVital = (VitalSign)model.getValueAt(selectedRow, 0);
        
        history.deleteVital(selectedVital);
        
        JOptionPane.showMessageDialog(this, "Vital Sign deleted", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        populateTable();
        
        fieldDate.setText("");
        fieldTemperature.setText("");
        fieldBp.setText("");
        fieldPulse.setText("");
        lblStatus.setText("");

    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JTextField fieldBp;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldPulse;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBp;
    private javax.swing.JLabel lblConcious;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JTable tblVital;
    // End of variables declaration//GEN-END:variables
}
